
      SUBROUTINE SBORN_FACTORIZED(CONTRIBUTION,EVENT_SLOT,WGT)
      IMPLICIT NONE
      INTEGER CONTRIBUTION,EVENT_SLOT
      DOUBLE PRECISION WGT
      WRITE(*,*) 'Explicit density Born called for a legacy process'
      STOP 1
      END

      SUBROUTINE SBORN_FACTORIZED_CHANNEL_WEIGHTS(P)
      IMPLICIT NONE
      INCLUDE 'nexternal.inc'
      DOUBLE PRECISION P(0:3,NEXTERNAL-1)
C     Legacy processes obtain their channel weights from SBORN itself.
      END

      SUBROUTINE SBORN_SF_FACTORIZED(CONTRIBUTION,EVENT_SLOT,
     $ M,N,WGT)
      IMPLICIT NONE
      INTEGER CONTRIBUTION,EVENT_SLOT,M,N
      DOUBLE PRECISION WGT
      WRITE(*,*) 'Explicit density color Born called for a legacy'
     $ //' process'
      STOP 1
      END

      SUBROUTINE SMATRIX_REAL_FACTORIZED(CONFIGURATION,EVENT_SLOT,WGT)
      IMPLICIT NONE
      INTEGER CONFIGURATION,EVENT_SLOT
      DOUBLE PRECISION WGT
      WRITE(*,*) 'Explicit density real called for a legacy process'
      STOP 1
      END

      SUBROUTINE SDM_SLOOPMATRIX_THRES(CONTRIBUTION,EVENT_SLOT,
     $ ANS,PREC_ASKED,PREC_FOUND,RET_CODE)
      IMPLICIT NONE
      INTEGER CONTRIBUTION,EVENT_SLOT,RET_CODE
      DOUBLE PRECISION ANS(0:3,0:1),PREC_ASKED,PREC_FOUND(0:1)
      WRITE(*,*) 'Explicit density virtual called for a legacy process'
      STOP 1
      END

      SUBROUTINE SDM_SLOOPMATRIXHEL_THRES(CONTRIBUTION,EVENT_SLOT,
     $ HEL,ANS,PREC_ASKED,PREC_FOUND,RET_CODE)
      IMPLICIT NONE
      INCLUDE 'nexternal.inc'
      INTEGER CONTRIBUTION,EVENT_SLOT,HEL(NEXTERNAL-1),RET_CODE
      DOUBLE PRECISION ANS(0:3,0:1),PREC_ASKED,PREC_FOUND(0:1)
      WRITE(*,*) 'Explicit density virtual called for a legacy process'
      STOP 1
      END

      SUBROUTINE SDM_FORCE_STABILITY_CHECK(CONTRIBUTION,ONOFF)
      IMPLICIT NONE
      INTEGER CONTRIBUTION
      LOGICAL ONOFF
      WRITE(*,*) 'Explicit density virtual called for a legacy process'
      STOP 1
      END

      SUBROUTINE SDM_COLLIER_COMPUTE_UV_POLES(CONTRIBUTION,ONOFF)
      IMPLICIT NONE
      INTEGER CONTRIBUTION
      LOGICAL ONOFF
      WRITE(*,*) 'Explicit density virtual called for a legacy process'
      STOP 1
      END

      SUBROUTINE SDM_COLLIER_COMPUTE_IR_POLES(CONTRIBUTION,ONOFF)
      IMPLICIT NONE
      INTEGER CONTRIBUTION
      LOGICAL ONOFF
      WRITE(*,*) 'Explicit density virtual called for a legacy process'
      STOP 1
      END

      INTEGER FUNCTION SDM_GETORDPOWFROMINDEX_ML5(CONTRIBUTION,
     $ IORDER,IAMP)
      IMPLICIT NONE
      INTEGER CONTRIBUTION,IORDER,IAMP
      WRITE(*,*) 'Explicit density virtual called for a legacy process'
      STOP 1
      END

      INTEGER FUNCTION SDM_BRANCH_COMPONENT_COUNT()
      IMPLICIT NONE
      SDM_BRANCH_COMPONENT_COUNT=1
      END

      INTEGER FUNCTION SDM_BRANCH_CORRECTED_COUNT()
      IMPLICIT NONE
      SDM_BRANCH_CORRECTED_COUNT=1
      END

      INTEGER FUNCTION SDM_BRANCH_MAX_OPEN_SIZE()
      IMPLICIT NONE
      SDM_BRANCH_MAX_OPEN_SIZE=1
      END

      INTEGER FUNCTION SDM_BRANCH_COMPONENT_ID(I)
      IMPLICIT NONE
      INTEGER I
      SDM_BRANCH_COMPONENT_ID=0
      END

      INTEGER FUNCTION SDM_BRANCH_COMPONENT_OPEN_SIZE(I)
      IMPLICIT NONE
      INTEGER I
      SDM_BRANCH_COMPONENT_OPEN_SIZE=1
      END

      INTEGER FUNCTION SDM_LEAF_MAX_PARTICLE_COUNT()
      IMPLICIT NONE
      SDM_LEAF_MAX_PARTICLE_COUNT=1
      END

      INTEGER FUNCTION SDM_LEAF_MAX_BLOCK_SIZE()
      IMPLICIT NONE
      SDM_LEAF_MAX_BLOCK_SIZE=1
      END

      SUBROUTINE SDM_LEAF_BLOCK_LAYOUT(I,J,K,L,A,B,C,D)
      IMPLICIT NONE
      INTEGER I,J,K,L,A(*),B(*),C(*),D(*)
      WRITE(*,*) 'Leaf layout called for a legacy process'
      STOP 1
      END

      LOGICAL FUNCTION SDM_COMPONENT_IS_CORRECTED(I)
      IMPLICIT NONE
      INTEGER I
      SDM_COMPONENT_IS_CORRECTED=.FALSE.
      END

      SUBROUTINE SDM_COMPONENT_BORN_DENSITY(I,J,K,L,M,RHO)
      IMPLICIT NONE
      INTEGER I,J,K,L,M
      COMPLEX*16 RHO(*)
      WRITE(*,*) 'Component Born density called for a legacy process'
      STOP 1
      END

      INTEGER FUNCTION SDM_CONTRIBUTION_COMPONENT_POSITION(I)
      IMPLICIT NONE
      INTEGER I
      SDM_CONTRIBUTION_COMPONENT_POSITION=1
      END

      LOGICAL FUNCTION SDM_VIRTUAL_USES_ANALYTIC_PROVIDER(I)
      IMPLICIT NONE
      INTEGER I
      SDM_VIRTUAL_USES_ANALYTIC_PROVIDER=.FALSE.
      END


      SUBROUTINE SDM_MULTIPLICATIVE_CONTRACTION(BRANCHES,CHOICE,
     $ WEIGHT_COUNT,RESULT)
      USE SPIN_DENSITY_MATRIX_RESULTS
      IMPLICIT NONE
      TYPE(SPIN_DENSITY_BRANCH_RESULT) BRANCHES(*)
      INTEGER CHOICE(*),WEIGHT_COUNT
      COMPLEX*16 RESULT(*)
      WRITE(*,*) 'Multiplicative contraction called for a legacy'
     $ //' process'
      STOP 1
      END
